let str = ''
str += '<head>'
str += '    <title>三国杀打小抄</title>'
str += '    <meta charset=UTF-8>'
str += '    <style type=text/css>'
str += '        ::-webkit-scrollbar {'
str += '            width: 5px;'
str += '            height: 12px;'
str += '        }'
str += ''
str += '        ::-webkit-scrollbar-track {'
str += '            border: 1px solid rgb(5, 5, 5);'
str += '        }'
str += ''
str += '        ::-webkit-scrollbar-thumb {'
str += '            background: rgb(95, 86, 63);'
str += '        }'
str += ''
str += '        ::-webkit-scrollbar-thumb:hover {'
str += '            background: rgb(44, 44, 44);'
str += '        }'
str += ''
str += '        * {'
str += '            width: 100%;'
str += '            margin: 0;'
str += '            padding: 0;'
str += '            font-size: 15px; /* 默认字体大小，可以根据需要调整 */'
str += '        }'
str += ''
str += '        @media screen and (min-width: 500px) {'
str += '            * {'
str += '                font-size: 1em; /* 在屏幕宽度大于500px时应用的字体大小 */'
str += '            }'
str += '        }'
str += ''
str += '        body {'
str += '            width: 100%;'
str += '            background: rgb(50, 50, 50);'
str += '            background-size: cover; /* 背景图的适应方式，可以根据需求调整 */'
str += '            color: #f2de9c;'
str += '            display: flex;'
str += '            flex-direction: column;'
str += '            margin: 0px;'
str += '            user-select: none;'
str += '        }'
str += ''
str += '        .nav {'
str += '            width: 100%;'
str += '            background: rgb(50, 50, 50);'
str += '        }'
str += ''
str += '        .nav1 {'
str += '            font-weight: bolder;'
str += ''
str += '            height: 20px;'
str += '            width: 100%;'
str += '            float: center;'
str += '            text-align: center;'
str += '            color: #f2de9c;'
str += '            background: rgb(50, 50, 50);'
str += '            s'
str += '            margin-right: 15px;'
str += '            display: block;'
str += '        }'
str += ''
str += '        .nav2 {'
str += '            height: 20px;'
str += '            width: 49%;'
str += '            float: right;'
str += '            text-align: center;'
str += '            color: #f2de9c;'
str += '            background: rgb(50, 50, 50);'
str += '            margin-left: 3px;'
str += '            border: 1px solid #f2de9c;'
str += '            display: block;'
str += '            border-radius: 5px;'
str += '        }'
str += ''
str += '        .nav2:hover {'
str += '            color: #f2de9c;'
str += '            background: rgb(55, 40, 32);'
str += '            border: 1px solid #f2de9c;'
str += '        }'
str += ''
str += '        .nav2:focus {'
str += '            background: rgb(55, 40, 32);'
str += '            box-shadow: 1px 1px 3px #f2de9c;'
str += '        }'
str += ''
str += '        .content {'
str += '            width: 100%;'
str += '            float: right;'
str += '        }'
str += ''
str += '        .orderAndShouPai {'
str += '            width: 100%;'
str += '            overflow: hidden;'
str += '            display: inline-block;'
str += '        }'
str += ''
str += '        .order {'
str += '            width: 100%;'
str += '            overflow: hidden;'
str += '        }'
str += ''
str += '        .orderContainer {'
str += '            width: 100%;'
str += '            overflow: hidden;'
str += '        }'
str += ''
str += '        .order-head {'
str += '            font-weight: bolder;'
str += '            width: 10%;'
str += '            height: 25px;'
str += '            float: left;'
str += '            text-align: center;'
str += '            color: #f2de9c;'
str += '            margin-left: 3px;'
str += '        }'
str += ''
str += '        .order-body:empty {'
str += '            padding: 5px;'
str += '            height: 35px;'
str += '            width: 81%;'
str += '            float: right;'
str += '            display: block;'
str += '            box-shadow: 1px 1px 3px;'
str += '            margin: 1px;'
str += '            overflow: hidden;'
str += '            border-radius: 5px;'
str += '        }'
str += ''
str += '        .order-body {'
str += '            padding: 5px;'
str += '            height: auto;'
str += '            width: 81%;'
str += '            float: right;'
str += '            display: block;'
str += '            box-shadow: 1px 1px 3px;'
str += '            margin: 1px;'
str += '            overflow: hidden;'
str += '            border-radius: 5px;'
str += '        }'
str += ''
str += '        .shoupai {'
str += '            --shoupaiR-width: 35px;'
str += '            font-weight: bolder;'
str += '            margin-right: calc(28px - var(--shoupaiR-width));'
str += '            float: left;'
str += '            width: var(--shoupaiR-width);'
str += '            height: 40px;'
str += '            border: 1px solid black;'
str += '            text-align: center;'
str += '            color: black;'
str += '            background: rgb(200, 200, 166);'
str += '            box-shadow: inset 3px 3px 6px #111;'
str += '        }'
str += ''
str += '        .shoupaiR {'
str += '            --shoupaiR-width: 35px;'
str += '            font-weight: bolder;'
str += '            margin-right: calc(28px - var(--shoupaiR-width));'
str += '            float: left;'
str += '            width: var(--shoupaiR-width);'
str += '            height: 40px;'
str += '            border: 1px solid black;'
str += '            text-align: center;'
str += '            color: red;'
str += '            background: rgb(200, 200, 166);'
str += '            box-shadow: inset 3px 3px 6px #111;'
str += '        }'
str += ''
str += '        .knownShouPai {'
str += '            border: 1px rgb(50, 50, 50) solid;'
str += '            animation: blink 1s;'
str += '            animation-iteration-count: infinite;'
str += '        }'
str += ''
str += '        .knownCardsInHand {'
str += '            text-align: center;'
str += '            position: relative;'
str += '            overflow: hidden;'
str += '            display: none;'
str += '            height: 121px;'
str += '        }'
str += ''
str += '        .knownCards:empty {'
str += '            text-align: center;'
str += '            position: relative;'
str += '            overflow: hidden;'
str += '            display: none;'
str += '        }'
str += ''
str += '        .knownCards {'
str += '            width: 81%;'
str += '            text-align: center;'
str += '            position: relative;'
str += '            overflow: hidden;'
str += '            height: 121px;'
str += '        }'
str += ''
str += '        @keyframes blink {'
str += '            50% {'
str += '                border-color: #f2de9c;'
str += '            }'
str += '        }'
str += ''
str += '        .knownCards:after {'
str += '            text-align: center;'
str += "            content: '场上手牌';"
str += '            position: absolute;'
str += '            bottom: 0;'
str += '            right: 5px;'
str += '            z-index: -1;'
str += "            font: 800 20px 'Arial Black';"
str += '            -webkit-text-fill-color: transparent;'
str += '            -webkit-text-stroke-width: 1px;'
str += '        }'
str += ''
str += '        .ding {'
str += '            text-align: center;'
str += '            width: 100%;'
str += '            position: relative;'
str += '            height: auto;'
str += '            display: none;'
str += ''
str += '        }'
str += ''
str += '        .dingCards {'
str += '            text-align: center;'
str += '            position: relative;'
str += '            height: auto;'
str += '            min-height: 60px;'
str += '            display: none;'
str += '        }'
str += ''
str += '        .dingCards:after {'
str += "            content: '第一张为牌堆顶';"
str += '            position: absolute;'
str += '            bottom: 0;'
str += '            right: 5px;'
str += '            z-index: -1;'
str += "            font: 800 20px 'Arial Black';"
str += '            -webkit-text-fill-color: transparent;'
str += '            -webkit-text-stroke-width: 1px;'
str += '        }'
str += ''
str += '        .di {'
str += '            text-align: center;'
str += '            width: 100%;'
str += '            position: relative;'
str += '            height: auto;'
str += '            display: none;'
str += '        }'
str += ''
str += '        .diCards {'
str += '            text-align: center;'
str += '            position: relative;'
str += '            height: auto;'
str += '            min-height: 60px;'
str += '            display: none;'
str += ''
str += '        }'
str += ''
str += '        .diCards:after {'
str += "            content: '第一张为牌堆底';"
str += '            position: absolute;'
str += '            bottom: 0;'
str += '            right: 5px;'
str += '            z-index: -1;'
str += "            font: 800 20px 'Arial Black';"
str += '            -webkit-text-fill-color: transparent;'
str += '            -webkit-text-stroke-width: 1px;'
str += ''
str += '        }'
str += ''
str += '        .cardDetail {'
str += '            width: 100%;'
str += '            overflow: hidden;'
str += '            display: inline-block;'
str += '        }'
str += ''
str += '        .type {'
str += '            width: 100%;'
str += '            float: left;'
str += '        }'
str += ''
str += '        .cardTypeContainer {'
str += '            width: 100%;'
str += '            overflow: hidden;'
str += '            display: block;'
str += '        }'
str += ''
str += '        .type-head {'
str += '            width: 10%;'
str += '            float: left;'
str += '            text-align: center;'
str += '            color: #f2de9c;'
str += '            margin-left: 3px;'
str += '            display: block;'
str += '            overflow: hidden;'
str += '            cursor: pointer;'
str += '        }'
str += ''
str += '        .type-body {'
str += '            padding: 5px;'
str += '            width: 81%;'
str += '            float: right;'
str += '            display: block;'
str += '            box-shadow: 1px 1px 3px;'
str += '            margin: 1px;'
str += '            overflow: hidden;'
str += '            border-radius: 5px;'
str += '        }'
str += ''
str += '        .cardType {'
str += '            font-size: 12px;'
str += '            width: 25%;'
str += '            height: 22px;'
str += '            float: left;'
str += '            text-align: center;'
str += '            border: 1px;'
str += '            margin: 0px;'
str += '            background: rgb(200, 200, 166);'
str += '            box-shadow: inset 1px 1px 3px #000;'
str += '        }'
str += ''
str += '        .detail {'
str += '            width: 100%;'
str += '            float: left;'
str += '            overflow: hidden;'
str += '        }'
str += ''
str += '        .detail-head {'
str += '            width: 10%;'
str += '            height: 25px;'
str += '            float: left;'
str += '            text-align: center;'
str += '            color: #f2de9c;'
str += '            margin-left: 3px;'
str += '        }'
str += ''
str += '        .detail-body {'
str += '            padding: 5px;'
str += '            width: 81%;'
str += '            float: right;'
str += '            display: block;'
str += '            box-shadow: 1px 1px 3px;'
str += '            margin: 1px;'
str += '            border-radius: 5px;'
str += '            overflow: hidden;'
str += '        }'
str += ''
str += '        .r {'
str += '            color: rgb(240, 65, 85);'
str += '        }'
str += ''
str += '        .suitRec {'
str += '            width: 100%;'
str += '            float: left;'
str += '        }'
str += ''
str += '        .suit {'
str += '            width: 50%;'
str += '            float: left;'
str += '        }'
str += ''
str += '        #shandian {'
str += '            width: 100%;'
str += '            float: left;'
str += '        }'
str += ''
str += '        .function {'
str += '            width: 50%;'
str += '            float: left;'
str += '        }'
str += ''
str += '        .jizhan {'
str += '            width: 100%;'
str += '            float: left;'
str += '        }'
str += ''
str += '        .yanjiao {'
str += '            width: 100%;'
str += '            float: left;'
str += '        }'
str += ''
str += '        .calRes {'
str += '            width: 100%;'
str += '            height: 20px;'
str += '            float: left;'
str += '            text-align: center;'
str += '            color: #f2de9c;'
str += '            background: rgb(50, 50, 50);'
str += '            border: 1px solid #f2de9c;'
str += '            display: block;'
str += '            border-radius: 5px;'
str += '        }'
str += ''
str += '        .calRes:hover {'
str += '            color: #f2de9c;'
str += '            background: rgb(55, 40, 32);'
str += '            border: 1px solid #f2de9c;'
str += '        }'
str += ''
str += '        .mizhuBtn {'
str += '            width: 100%;'
str += '            height: 20px;'
str += '            float: left;'
str += '            text-align: center;'
str += '            color: #f2de9c;'
str += '            background: rgb(50, 50, 50);'
str += '            border: 1px solid #f2de9c;'
str += '            display: block;'
str += '            border-radius: 5px;'
str += '        }'
str += ''
str += '        .mizhuBtn:hover {'
str += '            color: #f2de9c;'
str += '            background: rgb(55, 40, 32);'
str += '            border: 1px solid #f2de9c;'
str += '        }'
str += ''
str += '        .mizhu {'
str += '            width: 100%;'
str += '            height: 20px;'
str += '            float: left;'
str += '            text-align: center;'
str += '            color: #f2de9c;'
str += '            background: rgb(50, 50, 50);'
str += '            margin-left: 3px;'
str += '            border: 1px solid #f2de9c;'
str += '            display: block;'
str += '            border-radius: 5px;'
str += '        }'
str += ''
str += '        .mizhu:hover {'
str += '            color: #f2de9c;'
str += '            background: rgb(55, 40, 32);'
str += '            border: 1px solid #f2de9c;'
str += '        }'
str += ''
str += '        #mySeatID1 {'
str += '            width: 46%;'
str += '            display: none;'
str += '            float: left;'
str += '        }'
str += ''
str += '        #mySeatID2 {'
str += '            width: 46%;'
str += '            display: none;'
str += '            float: left;'
str += '        }'
str += ''
str += '        .res {'
str += '            width: 100%;'
str += '            float: left;'
str += '        }'
str += ''
str += '        .tooltip {'
str += '            position: relative;'
str += '            display: inline-block;'
str += '            text-align: center;'
str += '        }'
str += ''
str += '        .tooltiptext {'
str += '            width: 200px; /* 设置 tooltip 宽度，根据需要调整 */'
str += '            visibility: hidden;'
str += '            background-color: black;'
str += '            top: 900px; /* 调整 tooltip 与按钮的垂直距离 */'
str += '            left: 50%; /* 将 left 设置为 50% */'
str += '            transform: translateX(-50%); /* 使 tooltip 水平居中 */'
str += '            color: #f2de9c;'
str += '            text-align: left;'
str += '            padding: 5px 10px; /* 调整 padding 样式 */'
str += '            border-radius: 6px;'
str += '            position: fixed; /* 使用 fixed 定位 */'
str += '            z-index: 1;'
str += '        }'
str += ''
str += '        #donate {'
str += '            position: relative;'
str += '            color: #f2de9c;'
str += '            display: inline-block;'
str += '            text-align: center;'
str += '        }'
str += ''
str += '        .uuid {'
str += '            position: relative;'
str += '            color: #f2de9c;'
str += '            display: inline-block;'
str += '            text-align: center;'
str += '            cursor: pointer; /* Change cursor to pointer on hover */'
str += ''
str += '        }'
str += ''
str += ''
str += '        .uuid:hover {'
str += '            background: rgb(55, 40, 32);'
str += '        }'
str += ''
str += '        .uuid:active {'
str += '            background: rgb(55, 40, 32);'
str += '        }'
str += ''
str += '        .tooltip .tooltiptext {'
str += '            width: 100%;'
str += '            visibility: hidden;'
str += '            background-color: black;'
str += '            top: 50%; /* 将 top 设为 50% */'
str += '            left: 50%;'
str += '            transform: translate(-50%, -50%); /* 使用 transform 属性进行居中 */'
str += '            color: #f2de9c;'
str += '            text-align: left;'
str += '            padding: 5px 0;'
str += '            border-radius: 6px;'
str += '            position: absolute;'
str += '            z-index: 1;'
str += '        }'
str += ''
str += '        .tooltip:hover .tooltiptext {'
str += '            visibility: visible;'
str += '        }'
str += ''
str += '        .footer {'
str += '            position: fixed;'
str += '            bottom: 0;'
str += '            left: 0;'
str += '            width: 100%;'
str += '            text-align: center;'
str += '        }'
str += ''
str += '        .width {'
str += '            width: 100%;'
str += '            height: 5px;'
str += '        }'
str += '    </style>'
str += "    <script async src='https://www.googletagmanager.com/gtag/js?id=G-5C3C11THB3'></script>"
str += '    <script>'
str += '        window.dataLayer = window.dataLayer || [];'
str += ''
str += '        function gtag() {'
str += '            dataLayer.push(arguments);'
str += '        }'
str += ''
str += "        gtag('js', new Date());"
str += "        gtag('config', 'G-5C3C11THB3');"
str += '    </script>'
str += '</head>'
str += ''
str += '<body>'
str += ''
str += "<div class='nav'>"
str += "    <div class='nav1' id='nav1'>当前牌堆：无</div>"
str += "    <a href='http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=KzXr_lLtDLXPB9uKGaySToCLhWJz6Xxi&authKey=iJ26uPsWz8OOblSauQRSf93zgROEMdZdxPuhHD9hSn8GgfGc%2B54YHgFsLEEF9His&noverify=0&group_code=562224095'"
str += "       id='donate' target='_blank'>加群一起玩</a>"
str += '</div>'
str += "<div class='content' id='content'>"
str += "    <div class='orderAndShouPai' id='orderAndShouPai'>"
str += "        <div class='order' id='button'>"
str += "            <div class='orderContainer'>"
str += "                <div class='order-head or1' id='or1'>一</div>"
str += "                <div class='order-body No1' id='1'>"
str += "                    <button class='shoupaiR'>♦6 <br>测试</button>"
str += ''
str += '                </div>'
str += '            </div>'
str += "            <div class='orderContainer'>"
str += "                <div class='order-head or2' id='or2'>二</div>"
str += "                <div class=order-body No2 id='2'>"
str += "                    <button class='shoupai'>♦6 <br>卡牌</button>"
str += ''
str += '                </div>'
str += '            </div>'
str += "            <div class='orderContainer'>"
str += "                <div class='order-head or3' id='or3'>三</div>"
str += "                <div class=order-body No3 id='3'></div>"
str += '            </div>'
str += "            <div class='orderContainer'>"
str += "                <div class='order-head or4' id='or4'>四</div>"
str += "                <div class='order-body No4' id='4'></div>"
str += '            </div>'
str += "            <div class='orderContainer'>"
str += "                <div class='order-head or5' id='or5'>五</div>"
str += "                <div class='order-body No5' id='5'></div>"
str += '            </div>'
str += "            <div class='orderContainer'>"
str += "                <div class='order-head or6' id='or6'>六</div>"
str += "                <div class='order-body No6' id='6'></div>"
str += '            </div>'
str += "            <div class='orderContainer'>"
str += "                <div class='order-head or7' id='or7'>七</div>"
str += "                <div class='order-body No7' id='7'></div>"
str += '            </div>'
str += "            <div class='orderContainer'>"
str += "                <div class='order-head or8' id='or8'>八</div>"
str += "                <div class='order-body No8' id='8'></div>"
str += '            </div>'
str += "            <div class='orderContainer'>"
str += "                <div class='order-head knownCardsInHand' id='knownCardsInHand'>场上手牌</div>"
str += "                <div class='order-body knownCards' id='knownCards'></div>"
str += ''
str += '            </div>'
str += "            <div class='orderContainer'>"
str += "                <div class='order-head ding' id='ding'></div>"
str += "                <div class='order-body dingCards' id='dingCards'>"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += '                </div>'
str += '            </div>'
str += "            <div class='orderContainer'>"
str += "                <div class='order-head di' id='di'></div>"
str += "                <div class='order-body diCards' id='diCards'>"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += "                    <!--                                      <button class='shoupaiR'>♦6 <br>酒 </button>-->"
str += '                </div>'
str += '            </div>'
str += '        </div>'
str += '    </div>'
str += "    <div class='cardDetail' id='cardDetail'>"
str += '        <div class=space></div>'
str += '        <div class=detail>'
str += "            <div class='detail-head' id='detail'>"
str += '                <b>功能</b>'
str += '            </div>'
str += "            <div class='detail-body'>"
str += "                <div class='suit r' id='heart'>♥红桃 ×</div>"
str += "                <div class='suit' id='spade'>♠黑桃 ×</div>"
str += "                <div class='suit' id='club'>♣梅花 ×</div>"
str += "                <div class='suit r' id='diamond'>♦方片 ×</div>"
str += "                <div class='suit r' id='hongsha'>红杀 ×</div>"
str += "                <div class='suit' id='heisha' n>黑杀 ×</div>"
str += "                <div class='suitRec' id='suit'>乱击/权变花色</div>"
str += "                <div class='suitRec' id='boTu'>博图花色</div>"
str += "                <div class='function jizhan' id='jizhan'>吉占点数</div>"
str += "                <div class='function yanjiao' id='yanjiao'>严教小抄</div>"
str += "                <button class='function mizhuBTN' id='mizhu'>糜竺小抄</button>"
str += "                <button class='function mizhu mySeatID' id='mySeatID1'>座位：1</button>"
str += "                <button class='function mizhu mySeatID' id='mySeatID2'>座位：2</button>"
str += "                <div class='function res' id='res'>结果样式：1 1 1 1 = 4</div>"
str += '            </div>'
str += '        </div>'
str += "        <div class='width'></div>"
str += '        <div class=type>'
str += "            <div class='cardTypeContainer'>"
str += "                <div class='type-head' id='jiben'><b>基本</b></div>"
str += "                <div class='type-body type1' id='type1'>"
str += '                    <button class=cardType>12寒冰</button>'
str += '                </div>'
str += '            </div>'
str += "            <div class='cardTypeContainer'>"
str += "                <div class='type-head' id='jinnang'><b>锦囊</b></div>"
str += "                <div class='type-body type2' id='type2'>"
str += '                    <button class=cardType>12寒冰</button>'
str += '                </div>'
str += '            </div>'
str += "            <div class='cardTypeContainer'>"
str += "                <div class='type-head' id='zhuangbei'><b>装备</b></div>"
str += "                <div class='type-body type3' id='type3'>"
str += "                    <button class='cardType tooltip'>12寒冰</button>"
str += "                    <!--                                  <span class='tooltiptext'>-->"
str += '                    <!--                                    这是按钮3的说明内容。<br>-->'
str += '                    <!--                                    可以包含多行文本或其他元素。-->'
str += '                    <!--                                </span>-->'
str += '                </div>'
str += ''
str += '            </div>'
str += '        </div>'
str += '    </div>'
str += "    <!--        <div class='tooltip' >查看说明-->"
str += '    <!--                  <span class=tooltiptext>               <div>说明</div>-->'
str += '    <!--                <li>插件在军争、国战自动打开</li>-->'
str += '    <!--                <li>牌堆指的是未知牌堆，包括未知手牌和剩余牌堆的牌</li>-->'
str += '    <!--                <li>洗牌后可以计算出场上未知手牌，相当于攻心全场</li>-->'
str += '    <!--                <li>严教计算器自动出结果</li>-->'
str += '    <!--                <li>使用前可以先用演武看看功能</li>-->'
str += '    <!--                <li>其他牌堆和功能逐步完善，如果没被ban的话</li>-->'
str += '    <!--                <li>有任何问题或者建议可以添加群：562224095</li>-->'
str += '    <!--        </span>-->'
str += '    <!--        </div>-->'
str += '    <br>'
str += "    <a href='https://afdian.net/@yimadaO_o' id='donate' target='_blank'>请我喝肥宅快乐水</a>"
str += '    <br>'
str += "    <div class='uuid id' id='uuid'>id：123456789</div>"
// str += "    <div class='uuid nickName' id='nickName'>昵称：西瓜</div>";
str += '</div>'
str += '</body>'

export default str
